apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow
  labels:
    app: bms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms-app
  template:
    metadata:
      labels:
        app: bms-app
    spec:
      containers:
        - name: bms-container
          image: kanthi123/bms:latest
          ports:
            - containerPort: 3000
