apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: gopi2353/bookmyshow-app:latest
        ports:
        - containerPort: 3000
