apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaybms-app
  labels:
    app: udaybms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udaybms
  template:
    metadata:
      labels:
        app: udaybms
    spec:
      containers:
      - name: uday-bms-container
        image: udaykiran1218/bms:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
