apiVersion: v1
kind: Service
metadata:
  name: bms-service
spec:
  type: LoadBalancer
  selector:
    app: bms-app
  ports:
    - protocol: TCP
      port: 80       # external port
      targetPort: 3000  # container app port
