apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - port: 80        # external port
      targetPort: 3000 # container port
