apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms
          image: prasanna394/bms-app:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: bms-service
spec:
  selector:
    app: bms
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: LoadBalancer
